title: "DSA Notes"
description: "A collection of my Data Structures and Algorithms notes"
baseurl: "" # Leave empty if hosted on GitHub Pages with a custom domain
url: "https://manjunathbase2.github.io/astro-prep" # Update with your GitHub Pages URL
theme: minima # Default theme, or replace with another Jekyll theme
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude non-content files/folders from the build process
exclude:
  - README.md
  - .gitignore

# Navigation menu (optional)
collections:
  fundamentals:
    output: true
    permalink: /fundamentals/:path/
  data_structures:
    output: true
    permalink: /data_structures/:path/
  algorithms:
    output: true
    permalink: /algorithms/:path/

# Plugins (optional, add if needed)
plugins:
  - jekyll-feed # For RSS feed generation
  - jekyll-seo-tag # For SEO optimization

# Optional pagination settings
paginate: 5
paginate_path: "/page:num/"
