title: DSA Study Notes
remote_theme: just-the-docs/just-the-docs

# Enable automatic navigation without needing front matter
just_the_docs:
  collections:
    notes:
      name: "DSA Notes"
      output: true
  nav_sort: case_sensitive # Ensures folders appear in order
  collapse_sections: true  # Collapses sections for better navigation

# Enable relative paths to work outside `_docs/`
include:
  - "*.md"
  - "**/*.md"

baseurl: "/astro-prep"
