title: DSA Study Notes
remote_theme: just-the-docs/just-the-docs


# Enable hierarchical navigation automatically
collections:
  01-Fundatmentals:
    output: true
    permalink: pretty

# Enable automatic navigation without needing front matter
just_the_docs:
  collections:
    notes:
      name: "DSA Notes"
      output: true
  # Sort pages by folders
  nav_sort: "folder"
  collapse_sections: true  # Collapses sections for better navigation
  permalink: pretty
  toc_min_headings: 2  # Minimum number of headings to show in TOC

# Disable manual nav editing
nav_enabled: false

# Enable relative paths to work outside `_docs/`
include:
  - "*.md"
  - "**/*.md"

baseurl: "/astro-prep"
