title: DSA Study Notes
remote_theme: just-the-docs/just-the-docs

# Define the order of sections in the sidebar
# nav_order: 1

# Enable collections for subfolders
collections:
  00-MetaInfo:
    name: "00-Meta Info"
    nav_order: 1
    output: true
  01-Fundamentals:
    name: "01-Fundamentals"
    nav_order: 2
    output: true
  02-Data-Structures:
    name: "02-Data Structures"
    nav_order: 3
    output: true
  03-Algorithms:
    name: "03-Algorithms"
    nav_order: 4
    output: true
  04-Misc:
    name: "04-Misc"
    nav_order: 5
    output: true
  05-Resources:
    name: "05-Resources"
    nav_order: 6
    output: true

# # Define navigation structure explicitly
# nav:
#   - title: "DSA Study Notes"
#     url: /
#     nav_order: 1
#   - title: "01-Fundamentals"
#     url: /01-Fundamentals/
#     nav_order: 2
#   - title: "02-Data Structures"
#     url: /02-Data-Structures/
#     nav_order: 3
#   - title: "03-Algorithms"
#     url: /03-Algorithms/
#     nav_order: 4
#   - title: "Appendix"
#     url: /Appendix/
#     nav_order: 5
just_the_docs:
  show_toc: false
baseurl: "/astro-prep"
